apiVersion: v1
kind: ConfigMap
metadata:
  name: bibliokeep-vars
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/postgres
  SPRING_PROFILES_ACTIVE: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliokeep-backend
spec:
  selector:
    matchLabels:
      app: bibliokeep-be
  template:
    metadata:
      labels:
        app: bibliokeep-be
    spec:
      containers:
      - name: backend
        image: 'cesardevsenior/bibliokeep-backend'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef: { name: bibliokeep-vars }
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: { secretKeyRef: { name: db-secret, key: username } }
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secret, key: password } }
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bibliokeep-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: bibliokeep-be
  ports:
  - port: 8080
    targetPort: 8080
